### ISSUE TITLE
Conflict with bufferline plugin

### ISSUE THREAD

**Issue by askfiy** [vladdoster/remember.nvim#1] opened 2022-05-15 11:47 UTC
A bug that has been bothering me for a long time, after I disabled this plugin, bufferline is normal...

Specifically, you can see [bufferline -> #416](https://github.com/akinsho/bufferline.nvim/issues/416)

If you want to reproduce it, press the key and keep moving the buffer.

**Comment by vladdoster** [comment] 2022-06-08 21:25
@askfiy How are you sure it is this plugin?

**Comment by askfiy** [comment] 2022-06-09 02:20
Since I stopped using the plug-in, everything has worked. This situation has never happened again

**Comment by vladdoster** [comment] 2022-06-09 11:14
I would be pretty confident in saying the issue was not caused by this plugin. 

If you start using this plugin in the future and the issue returns, we can get to the bottom to the issue. 

Due to you not using this plugin, Im closing this issue.

Feel free to reopen if you you have further questions/comments 👍.

**Closed as not planned** 2022-06-09 11:14 UTC
